# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, verbose_name="관리자 명(ROLE_ADMIN)"
                    ),
                ),
                ("nickname", models.TextField(default="관리자")),
            ],
            options={
                "verbose_name": "관리자",
                "db_table": "authority",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("title_ko", models.CharField(max_length=1000, null=True)),
                ("title_en", models.CharField(max_length=1000, null=True)),
                ("title_ja", models.CharField(max_length=1000, null=True)),
                ("title_zh", models.CharField(max_length=1000, null=True)),
                ("title_fr", models.CharField(max_length=1000, null=True)),
                ("title_es", models.CharField(max_length=1000, null=True)),
                ("title_pt", models.CharField(max_length=1000, null=True)),
                ("title_ru", models.CharField(max_length=1000, null=True)),
                ("title_de", models.CharField(max_length=1000, null=True)),
                ("title_ar", models.CharField(max_length=1000, null=True)),
                ("title_hi", models.CharField(max_length=1000, null=True)),
                ("content", models.TextField()),
                ("content_ko", models.TextField(null=True)),
                ("content_en", models.TextField(null=True)),
                ("content_ja", models.TextField(null=True)),
                ("content_zh", models.TextField(null=True)),
                ("content_fr", models.TextField(null=True)),
                ("content_es", models.TextField(null=True)),
                ("content_pt", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("content_de", models.TextField(null=True)),
                ("content_ar", models.TextField(null=True)),
                ("content_hi", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "db_table": "faq",
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_ja",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_zh",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_es",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_pt",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "title_hi",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="title 은 관리자에서 빨리 찾을 수 있게 일단 만듦",
                    ),
                ),
                (
                    "gift_img",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_ko",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_en",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_ja",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_zh",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_fr",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_es",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_pt",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_ru",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_de",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_ar",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
                (
                    "gift_img_hi",
                    models.ImageField(blank=True, null=True, upload_to="uploads/gift/"),
                ),
            ],
            options={
                "verbose_name": "사은품 및 광고",
                "db_table": "gift",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("title_ko", models.CharField(max_length=1000, null=True)),
                ("title_en", models.CharField(max_length=1000, null=True)),
                ("title_ja", models.CharField(max_length=1000, null=True)),
                ("title_zh", models.CharField(max_length=1000, null=True)),
                ("title_fr", models.CharField(max_length=1000, null=True)),
                ("title_es", models.CharField(max_length=1000, null=True)),
                ("title_pt", models.CharField(max_length=1000, null=True)),
                ("title_ru", models.CharField(max_length=1000, null=True)),
                ("title_de", models.CharField(max_length=1000, null=True)),
                ("title_ar", models.CharField(max_length=1000, null=True)),
                ("title_hi", models.CharField(max_length=1000, null=True)),
                (
                    "news_img",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_ko",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_en",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_ja",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_zh",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_fr",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_es",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_pt",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_ru",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_de",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_ar",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                (
                    "news_img_hi",
                    models.ImageField(blank=True, null=True, upload_to="uploads/news/"),
                ),
                ("news_description", models.TextField(verbose_name="해당 new 설명")),
                (
                    "news_description_ko",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_en",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_ja",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_zh",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_fr",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_es",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_pt",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_ru",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_de",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_ar",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "news_description_hi",
                    models.TextField(null=True, verbose_name="해당 new 설명"),
                ),
                (
                    "link",
                    models.CharField(
                        max_length=500,
                        verbose_name="이벤트나 어떤 llm 모델을 소개해주고 싶을떄 소개하는 페이지 아래 칸에 넣을 url 경로",
                    ),
                ),
            ],
            options={
                "verbose_name": "뉴스",
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="쿠폰 코드")),
                ("description", models.TextField(verbose_name="쿠폰 설명")),
                (
                    "description_ko",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_ja",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_zh",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_fr",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_es",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_pt",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_de",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_ar",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                (
                    "description_hi",
                    models.TextField(null=True, verbose_name="쿠폰 설명"),
                ),
                ("start_day", models.DateTimeField(verbose_name="쿠폰 시작일")),
                ("end_day", models.DateTimeField(verbose_name="쿠폰 만료일")),
                ("is_activate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coupon",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_ko", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_ja", models.CharField(max_length=200, null=True)),
                ("title_zh", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("title_pt", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_de", models.CharField(max_length=200, null=True)),
                ("title_ar", models.CharField(max_length=200, null=True)),
                ("title_hi", models.CharField(max_length=200, null=True)),
                ("content", models.TextField()),
                ("content_ko", models.TextField(null=True)),
                ("content_en", models.TextField(null=True)),
                ("content_ja", models.TextField(null=True)),
                ("content_zh", models.TextField(null=True)),
                ("content_fr", models.TextField(null=True)),
                ("content_es", models.TextField(null=True)),
                ("content_pt", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("content_de", models.TextField(null=True)),
                ("content_ar", models.TextField(null=True)),
                ("content_hi", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "db_table": "notice",
            },
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("title", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("is_secret", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "요청 사항",
                "db_table": "requests",
            },
        ),
        migrations.CreateModel(
            name="UserAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_auth.authority",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Authority",
                "verbose_name_plural": "User Authorities",
                "db_table": "user_auth",
                "unique_together": {("user", "authority")},
            },
        ),
    ]
