# Generated by Django 5.2.4 on 2025-08-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="upload/celebrity_images/"
            ),
        ),
    ]
