# Generated by Django 5.2.4 on 2025-08-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_celebrity_celebrity_image"),
    ]

    operations = []
