# Generated by Django 5.2.4 on 2025-08-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_auto_20250801_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_voice_id",
            field=models.CharField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
