# Generated by Django 5.2.4 on 2025-09-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_referral"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="referral",
            table="referral",
        ),
    ]
