# Generated by Django 5.2.4 on 2025-08-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_celebrity_celebrity_voice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celebrity",
            name="celebrity_voice_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
