# Generated by Django 5.2.4 on 2025-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_alter_referral_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
