# Generated by Django 5.2.4 on 2025-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0005_alter_celebrity_celebrity_voice_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celebrity",
            name="celebrity_image",
        ),
        migrations.AddField(
            model_name="celebrity",
            name="llm_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/celebrity_images/"
            ),
        ),
    ]
