# Generated by Django 5.2.4 on 2025-09-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0005_referral_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gift",
            options={"verbose_name": "이벤트"},
        ),
    ]
