# Generated by Django 5.2.4 on 2025-09-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0006_alter_gift_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
