# Generated by Django 5.2.4 on 2025-08-03 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0006_remove_celebrity_celebrity_image_celebrity_llm_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celebrity",
            old_name="llm_image",
            new_name="celebrity_image",
        ),
    ]
