# Generated by Django 5.2.4 on 2025-08-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0007_rename_llm_image_celebrity_celebrity_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celebrity",
            name="voice",
        ),
        migrations.AddField(
            model_name="celebrity",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="celebrities",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
