# Generated by Django 5.2.4 on 2025-08-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0009_alter_celebrity_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celebrity",
            name="user",
        ),
    ]
