# Generated by Django 5.2.4 on 2025-08-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0010_remove_celebrity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_fr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_hi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_ja",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_ko",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="celebrity_name_zh",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_hi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_ja",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_ko",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="celebrity",
            name="description_zh",
            field=models.TextField(null=True),
        ),
    ]
