# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "결제 수단",
                "verbose_name_plural": "결제 수단들",
                "db_table": "payment_method",
            },
        ),
        migrations.CreateModel(
            name="PaymentRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rankname",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="결제 등급"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="등급에 따른 가격"
                    ),
                ),
                (
                    "voicetime",
                    models.CharField(
                        max_length=100, verbose_name="가격에 따른 음성 시간"
                    ),
                ),
                (
                    "freetoken",
                    models.IntegerField(
                        null=True, verbose_name="등급에 따른 무료 토큰 횟수"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFF", max_length=100, verbose_name="등급에 따른 색깔"
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 등급",
                "verbose_name_plural": "결제 등급",
                "db_table": "payment_rank",
            },
        ),
        migrations.CreateModel(
            name="PaymentStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_payments",
                    models.PositiveIntegerField(default=0, verbose_name="총 결제 횟수"),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="성공 결제 횟수"
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="실패 결제 횟수"
                    ),
                ),
                (
                    "pending_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="대기 결제 횟수"
                    ),
                ),
                (
                    "refunded_count",
                    models.PositiveIntegerField(default=0, verbose_name="환불 횟수"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "결제 통계",
                "verbose_name_plural": "결제 통계",
                "db_table": "payment_stats",
            },
        ),
        migrations.CreateModel(
            name="TotalToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_tokens_used", models.BigIntegerField(default=0)),
                ("total_llm_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Total Token",
                "verbose_name_plural": "Total Tokens",
                "db_table": "total_token",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="실제 결제된 금액 기록",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("pending", "Pending"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="결제한 날짜"),
                ),
                (
                    "imp_uid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="결제 번호"
                    ),
                ),
                (
                    "merchant_uid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="주문번호"
                    ),
                ),
                (
                    "apply_num",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="PG 승인 번호",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KRW", max_length=10, verbose_name="결제 통화 기록"
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, null=True, verbose_name="환불 사유"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저 id 정보",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment.paymentmethod",
                        verbose_name="결제 방식",
                    ),
                ),
                (
                    "payment_rank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment.paymentrank",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 수단, 관리",
                "db_table": "payment",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_token", models.DecimalField(decimal_places=2, max_digits=10)),
                ("token_usage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TOKEN",
                "verbose_name_plural": "TOKENS",
                "db_table": "token",
            },
        ),
        migrations.CreateModel(
            name="TokenHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("charge", "Charge"), ("consume", "Consume")],
                        max_length=10,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_voice_generated", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token History",
                "verbose_name_plural": "Token Histories",
                "db_table": "token_history",
            },
        ),
    ]
