# Generated by Django 5.2.4 on 2025-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="total_token",
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
    ]
