# Generated by Django 5.2.4 on 2025-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_token_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token_usage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_token",
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10),
        ),
    ]
