# Generated by Django 5.2.4 on 2025-08-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_token_token_usage_alter_token_total_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer_uid",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="PG 사 발급 토큰"
            ),
        ),
    ]
