# Generated by Django 5.2.4 on 2025-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_payment_customer_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrank",
            name="daller_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="등급에 따른 가격(달러)",
            ),
            preserve_default=False,
        ),
    ]
