# Generated by Django 5.2.4 on 2025-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_paymentrank_daller_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="payment_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
