# Generated by Django 5.2.4 on 2025-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_paymentmethod_payment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="total_token",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
