# Generated by Django 5.2.4 on 2025-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_alter_token_total_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_ar",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_es",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_fr",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_hi",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_ja",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_ko",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_pt",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
        migrations.AddField(
            model_name="paymentrank",
            name="voicetime_zh",
            field=models.CharField(
                max_length=100, null=True, verbose_name="가격에 따른 음성 시간"
            ),
        ),
    ]
