# Generated by Django 5.2.4 on 2025-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_paymentrank_voicetime_ar_paymentrank_voicetime_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="channel_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="currency",
            field=models.CharField(default="KRW", max_length=10),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="extra_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="imp_merchant_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
