# Generated by Django 5.2.4 on 2025-09-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0015_alter_llm_model"),
        ("payment", "0010_paymentmethod_channel_key_paymentmethod_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenhistory",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_histories",
                to="customer_ai.llm",
            ),
        ),
    ]
