# Generated by Django 5.2.4 on 2025-10-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_tokenhistory_llm"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="환불 완료 날짜"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("pending", "Pending"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_token",
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tokenhistory",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("charge", "Charge"),
                    ("consume", "Consume"),
                    ("refund", "Refund"),
                ],
                max_length=10,
            ),
        ),
    ]
