# Generated by Django 5.2.4 on 2025-10-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_payment_refunded_at_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="refund_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("pending", "Pending"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("refund_pending", "환불 대기"),
                ],
                max_length=20,
            ),
        ),
    ]
