# Generated by Django 5.2.4 on 2025-10-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_alter_payment_refund_reason_alter_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="refunded_at",
        ),
        migrations.AlterField(
            model_name="payment",
            name="refund_reason",
            field=models.TextField(blank=True, null=True, verbose_name="환불 사유"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("pending", "Pending"),
                    ("refunded", "Refunded"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tokenhistory",
            name="change_type",
            field=models.CharField(
                choices=[("charge", "Charge"), ("consume", "Consume")], max_length=10
            ),
        ),
    ]
