# Generated by Django 5.2.4 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_payment_refunded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='total_token',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
    ]
