# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("llm_response", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "대화목록",
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="user 가 지정한 LLM 이름"
                    ),
                ),
                ("prompt", models.TextField(verbose_name="user 가 지정한 프롬프트")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="user 가 LLM 을 만든 시기"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="user 가 프롬프트, 목소리 변형을 했을 경우 나중에 문제가 생겼을때 원인을 찾을 수 있음",
                    ),
                ),
                (
                    "llm_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/llm_images/"
                    ),
                ),
                (
                    "response_mp3",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="해당 보이스를 저장할 수 있는 mp3 파일 -> 목소리는 ai가 대답할 떄마다 기록이 덮어씌워짐",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("gpt-4o-mini", "GPT-4o Mini"),
                            ("gpt-4o", "GPT-4o"),
                        ],
                        default="gpt-3.5-turbo",
                        max_length=20,
                        verbose_name="gpt 모델 중 하나를 선택해서 사용할 수 있음",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("temperature", models.FloatField(default=1.0)),
                ("stability", models.FloatField(default=0.5)),
                ("speed", models.FloatField(default=1.0)),
                ("style", models.FloatField(default=0.5)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="해당 LLM 을 공유 할 것인가?"
                    ),
                ),
                ("title", models.CharField(max_length=1000, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="해당 LLM 이 공유될떄 실행"
                    ),
                ),
                (
                    "llm_like_count",
                    models.IntegerField(
                        default=0, verbose_name="llm이 받은 좋아요 갯수"
                    ),
                ),
                (
                    "llm_background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/llm_background_images/",
                    ),
                ),
                ("invest_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "ai 정보",
                "db_table": "LLM",
            },
        ),
        migrations.CreateModel(
            name="LlmLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_like", models.BooleanField(null=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 좋아요",
                "db_table": "llm_like",
            },
        ),
    ]
