# Generated by Django 5.2.4 on 2025-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("stability", models.FloatField(default=0)),
                ("similarity", models.FloatField(default=0)),
                ("style", models.FloatField(default=0)),
                ("language", models.CharField(blank=True, max_length=20, null=True)),
                ("voice_id", models.CharField(blank=True, max_length=100, null=True)),
                ("speed", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
