# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_ai", "0001_initial"),
        ("makeVoice", "0001_initial"),
        ("mypage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="llms", to="mypage.genre"
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llms",
                to="makeVoice.voicelist",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="llm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_ai.llm"
            ),
        ),
        migrations.AddField(
            model_name="llmlike",
            name="llm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_lists",
                to="customer_ai.llm",
            ),
        ),
        migrations.AddField(
            model_name="llmlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="llmlike",
            unique_together={("user", "llm")},
        ),
    ]
