# Generated by Django 5.2.4 on 2025-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmlike",
            name="is_like",
            field=models.BooleanField(default=True),
        ),
    ]
