# Generated by Django 5.2.4 on 2025-08-18 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0004_alter_llm_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_title",
                    models.CharField(
                        max_length=100, verbose_name="프롬프트 제목 적는칸"
                    ),
                ),
                ("prompt", models.TextField(verbose_name="프롬프트 적는 칸")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "prompt 정보",
                "db_table": "prompt",
            },
        ),
    ]
