# Generated by Django 5.2.4 on 2025-08-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0005_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmlike",
            name="llm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like",
                to="customer_ai.llm",
            ),
        ),
    ]
