# Generated by Django 5.2.4 on 2025-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0006_alter_llmlike_llm"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="is_voice",
            field=models.BooleanField(
                default=False, verbose_name="목소리 프롬프트 여부"
            ),
        ),
    ]
