# Generated by Django 5.2.4 on 2025-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0007_prompt_is_voice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="is_voice",
        ),
        migrations.AddField(
            model_name="prompt",
            name="prompt_type",
            field=models.CharField(
                choices=[("text", "일반 프롬프트"), ("voice", "목소리 프롬프트")],
                default="text",
                max_length=10,
            ),
        ),
    ]
