# Generated by Django 5.2.4 on 2025-08-24 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0008_remove_prompt_is_voice_prompt_prompt_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
    ]
