# Generated by Django 5.2.4 on 2025-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0009_prompt_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="response_audio",
            field=models.FileField(
                blank=True, null=True, upload_to="conversation_audio/"
            ),
        ),
    ]
