# Generated by Django 5.2.4 on 2025-09-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0010_conversation_response_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="response_audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
