# Generated by Django 5.2.4 on 2025-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0011_alter_conversation_response_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="llm_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="uploads/llm_images/"
            ),
        ),
    ]
