# Generated by Django 5.2.4 on 2025-09-12 07:37

import customer_ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0012_alter_llm_llm_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="llm_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="uploads/llm_images/",
                validators=[customer_ai.models.validate_webp],
            ),
        ),
    ]
