# Generated by Django 5.2.4 on 2025-09-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_ai", "0014_alter_llm_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt:gpt-4o-mini", "GPT-4o Mini"),
                    ("grok:grok-3-mini", "Grok-3-mini "),
                ],
                default="gpt:gpt-4o-mini",
                max_length=20,
                verbose_name="gpt 모델 중 하나를 선택해서 사용할 수 있음",
            ),
        ),
    ]
