# Generated by Django 5.2.4 on 2026-01-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ai', '0015_alter_llm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/llm_sub_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='이미지 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='이미지 설명')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='customer_ai.llm')),
            ],
            options={
                'verbose_name': 'LLM 서브 이미지',
                'verbose_name_plural': 'LLM 서브 이미지들',
                'db_table': 'llm_sub_image',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
