# Generated by Django 5.2.4 on 2026-01-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ai', '0016_llmsubimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='first_sentence',
            field=models.TextField(null=True, verbose_name='첫 마디'),
        ),
    ]
