# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmBackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "default_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/default_img/"
                    ),
                ),
            ],
            options={
                "verbose_name": "llm 배경사진",
                "db_table": "llm_background_image",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="댓글")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_ai.llm",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replies",
                        to="distribute.comment",
                        verbose_name="답글 대상 댓글",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 대한 댓글창",
                "db_table": "comment",
            },
        ),
    ]
