# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_ai", "0002_initial"),
        ("distribute", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="llmbackgroundimage",
            name="llm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_ai.llm"
            ),
        ),
    ]
