# Generated by Django 5.2.4 on 2025-08-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distribute", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"], "verbose_name": ("AI 대한 댓글창",)},
        ),
    ]
