# Generated by Django 5.2.4 on 2025-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_ko", models.CharField(max_length=100, null=True, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_ja", models.CharField(max_length=100, null=True, unique=True)),
                ("name_zh", models.CharField(max_length=100, null=True, unique=True)),
                ("name_fr", models.CharField(max_length=100, null=True, unique=True)),
                ("name_es", models.CharField(max_length=100, null=True, unique=True)),
                ("name_pt", models.CharField(max_length=100, null=True, unique=True)),
                ("name_ru", models.CharField(max_length=100, null=True, unique=True)),
                ("name_de", models.CharField(max_length=100, null=True, unique=True)),
                ("name_ar", models.CharField(max_length=100, null=True, unique=True)),
                ("name_hi", models.CharField(max_length=100, null=True, unique=True)),
                (
                    "genre_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/genre_images/"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFF", max_length=10, verbose_name="태그 넣을떄 색깔"
                    ),
                ),
            ],
            options={
                "verbose_name": "장르",
                "db_table": "genres",
            },
        ),
    ]
