# Generated by Django 5.2.4 on 2025-07-30 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("llm_image", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "response_mp3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "models",
                    models.CharField(
                        choices=[
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("gpt-4o-mini", "GPT-4o Mini"),
                            ("gpt-4o", "GPT-4o"),
                        ],
                        default="gpt-3.5-turbo",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "llms",
            },
        ),
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice_id", models.CharField(max_length=200, unique=True)),
                ("stability", models.FloatField(default=0.5)),
                ("speed", models.FloatField(blank=True, default=1.0, null=True)),
                ("style", models.FloatField(default=0.5)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "preview_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("temperature", models.FloatField(default=1.0)),
            ],
            options={
                "db_table": "voice",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_image",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("llm_image", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "image",
            },
        ),
    ]
