# Generated by Django 5.2.4 on 2025-07-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="llm_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/llm_images/"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="user_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile_images/"
            ),
        ),
    ]
