# Generated by Django 5.2.4 on 2025-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0003_alter_image_llm_image_alter_image_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="llm_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/llm_images/"
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
