# Generated by Django 5.2.4 on 2025-07-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0004_alter_llm_llm_image_delete_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llm",
            old_name="models",
            new_name="model",
        ),
    ]
