# Generated by Django 5.2.4 on 2025-08-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0006_auto_20250801_1638"),
    ]

    operations = []
