# Generated by Django 5.2.4 on 2025-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0007_auto_20250801_1638"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voice",
            name="language",
        ),
        migrations.RemoveField(
            model_name="voice",
            name="speed",
        ),
        migrations.RemoveField(
            model_name="voice",
            name="stability",
        ),
        migrations.RemoveField(
            model_name="voice",
            name="style",
        ),
        migrations.RemoveField(
            model_name="voice",
            name="temperature",
        ),
        migrations.AddField(
            model_name="llm",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="llm",
            name="speed",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name="llm",
            name="stability",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="llm",
            name="style",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="llm",
            name="temperature",
            field=models.FloatField(default=1.0),
        ),
    ]
