# Generated by Django 5.2.4 on 2025-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Celebrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "celebrity_voice_id",
                    models.CharField(max_length=200, verbose_name="celebrity voiceid"),
                ),
                ("celebrity_name", models.CharField(max_length=100)),
                ("celebrity_name_ko", models.CharField(max_length=100, null=True)),
                ("celebrity_name_en", models.CharField(max_length=100, null=True)),
                ("celebrity_name_ja", models.CharField(max_length=100, null=True)),
                ("celebrity_name_zh", models.CharField(max_length=100, null=True)),
                ("celebrity_name_fr", models.CharField(max_length=100, null=True)),
                ("celebrity_name_es", models.CharField(max_length=100, null=True)),
                ("celebrity_name_pt", models.CharField(max_length=100, null=True)),
                ("celebrity_name_ru", models.CharField(max_length=100, null=True)),
                ("celebrity_name_de", models.CharField(max_length=100, null=True)),
                ("celebrity_name_ar", models.CharField(max_length=100, null=True)),
                ("celebrity_name_hi", models.CharField(max_length=100, null=True)),
                ("celebrity_prompt", models.TextField()),
                ("description", models.TextField()),
                ("description_ko", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("description_ja", models.TextField(null=True)),
                ("description_zh", models.TextField(null=True)),
                ("description_fr", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
                ("description_pt", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_de", models.TextField(null=True)),
                ("description_ar", models.TextField(null=True)),
                ("description_hi", models.TextField(null=True)),
                (
                    "celebrity_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/celebrity_images/"
                    ),
                ),
            ],
            options={
                "verbose_name": "celebrity 커스텀",
                "db_table": "celebrity",
            },
        ),
        migrations.CreateModel(
            name="CelebrityVoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="보이스 이름")),
                (
                    "name_ko",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_pt",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "name_hi",
                    models.CharField(
                        max_length=200, null=True, verbose_name="보이스 이름"
                    ),
                ),
                (
                    "sample_url",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="voices/",
                        verbose_name="보이스 목소리 url",
                    ),
                ),
                ("celebrity_voice_id", models.CharField(max_length=200)),
                (
                    "celebrity_voice_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/celebrity_voice_image/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "celebrity 보이스 목록",
                "db_table": "celebrity_voice",
            },
        ),
    ]
