# Generated by Django 5.2.4 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityvoice',
            name='sample_url',
            field=models.TextField(blank=True, null=True, verbose_name='ElevenLabs preview url'),
        ),
    ]
