# Generated by Django 5.2.4 on 2025-08-15 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sample_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("voice_name", models.CharField(max_length=100)),
                (
                    "voice_image",
                    models.ImageField(
                        blank=True,
                        default="uploads/voice_images/HOMEv.png/",
                        null=True,
                        upload_to="uploads/voice_images/HOME v.png/",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("voice_id", models.CharField(max_length=200)),
                (
                    "voice_like_count",
                    models.IntegerField(
                        default=0, verbose_name="보이스가 받은 좋아요 갯수"
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_ai.llm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "voice 리스트",
                "db_table": "voice_list",
            },
        ),
        migrations.CreateModel(
            name="VoiceLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="makeVoice.voicelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "voice 좋아요",
                "db_table": "voice_like",
            },
        ),
    ]
