# Generated by Django 5.2.4 on 2025-09-01 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0001_initial"),
        ("makeVoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicelist",
            name="celebrity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voices",
                to="celebrity.celebrityvoice",
            ),
        ),
    ]
