# Generated by Django 5.2.4 on 2025-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeVoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicelist",
            name="sample_url",
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
