# Generated by Django 5.2.4 on 2025-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeVoice", "0002_alter_voicelist_sample_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicelist",
            name="sample_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
