# Generated by Django 5.2.4 on 2025-09-01 02:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celebrity", "0001_initial"),
        ("makeVoice", "0002_voicelist_celebrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voicelist",
            unique_together={("user", "celebrity")},
        ),
    ]
