# Generated by Django 5.2.4 on 2025-07-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
