# Generated by Django 5.2.4 on 2025-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nickname", models.CharField(max_length=100, unique=True)),
                ("phonenumber", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
