# Generated by Django 5.2.4 on 2025-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_users_managers_remove_users_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="user_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile_images/"
            ),
        ),
    ]
