# Generated by Django 5.2.4 on 2025-08-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_users_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="nickname",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
