# Generated by Django 5.2.4 on 2025-09-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_users_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="uploads/profile_images/",
            ),
        ),
    ]
