# Generated by Django 5.2.4 on 2025-08-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_users_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=400),
        ),
    ]
