# Generated by Django 5.2.4 on 2025-08-27 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloningAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_voice",
                    models.BooleanField(
                        default=False, verbose_name="본인 음성 클로닝 동의"
                    ),
                ),
                (
                    "consent_third",
                    models.BooleanField(
                        default=False, verbose_name="타인 음성 사용 책임 인지"
                    ),
                ),
                (
                    "consent_share",
                    models.BooleanField(
                        default=False, verbose_name="클로닝 음성 공유 금지"
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="동의 일시"),
                ),
                ("voice_text", models.TextField(verbose_name="동의서 전문")),
                (
                    "voice_text_ko",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_en",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_ja",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_zh",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_fr",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_es",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_pt",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_ru",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_de",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_ar",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "voice_text_hi",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                ("third_text", models.TextField(verbose_name="동의서 전문")),
                (
                    "third_text_ko",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_en",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_ja",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_zh",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_fr",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_es",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_pt",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_ru",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_de",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_ar",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "third_text_hi",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                ("share_text", models.TextField(verbose_name="동의서 전문")),
                (
                    "share_text_ko",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_en",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_ja",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_zh",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_fr",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_es",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_pt",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_ru",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_de",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_ar",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "share_text_hi",
                    models.TextField(null=True, verbose_name="동의서 전문"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "보이스 클로닝 동의 항목",
                "db_table": "cloning_agreement",
            },
        ),
    ]
