# Generated by Django 5.2.4 on 2025-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text",
            field=models.TextField(verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_ar",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_de",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_en",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_es",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_fr",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_hi",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_ja",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_ko",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_pt",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_ru",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="share_text_zh",
            field=models.TextField(null=True, verbose_name="동의서 전문(share text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text",
            field=models.TextField(verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_ar",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_de",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_en",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_es",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_fr",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_hi",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_ja",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_ko",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_pt",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_ru",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="third_text_zh",
            field=models.TextField(null=True, verbose_name="동의서 전문(third text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text",
            field=models.TextField(verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_ar",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_de",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_en",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_es",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_fr",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_hi",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_ja",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_ko",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_pt",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_ru",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
        migrations.AlterField(
            model_name="cloningagreement",
            name="voice_text_zh",
            field=models.TextField(null=True, verbose_name="동의서 전문(voice text)"),
        ),
    ]
